version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ec2-user
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 500
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 600
      runas: root
